.PHONY: all clean algorithm game_manager simulator

all: algorithm game_manager simulator

algorithm:
	$(MAKE) -C Algorithm

game_manager:
	$(MAKE) -C GameManager

simulator:
	$(MAKE) -C Simulator

clean:
	$(MAKE) -C Algorithm clean
	$(MAKE) -C GameManager clean
	$(MAKE) -C Simulator clean
